apiVersion: v1
kind: Service
metadata:
  name: {{ include "openhab.fullname" . }}
  labels:
    {{- include "openhab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "openhab.selectorLabels" . | nindent 4 }}
{{- if .Values.service.lsp.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openhab.fullname" . }}-lsp
  labels:
    {{- include "openhab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.lsp.type }}
  ports:
    - port: {{ .Values.service.lsp.port }}
      targetPort: 5007
      protocol: TCP
      name: lsp
      {{- if .Values.service.lsp.nodePort }}
      nodePort: {{ .Values.service.lsp.nodePort }}
      {{- end }}
  selector:
    {{- include "openhab.selectorLabels" . | nindent 4 }}
{{- end }}
