apiVersion: v1
kind: Service
metadata:
  name: {{ include "proton-bridge.fullname" . }}
  labels:
    {{- include "proton-bridge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalIPs }}
  externalIPs: {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  ports:
    - name: smtp
      port: {{ .Values.service.ports.smtpPort }}
      targetPort: 1025
      protocol: TCP
  selector:
    {{- include "proton-bridge.selectorLabels" . | nindent 4 }}
